import pandas as pd

# ============================================================
# INDIA IMPORT EXPOSURE MODEL
# ============================================================

print("Loading India import exposure model...")

# Load the latest geopolitical risk generated by the risk pipeline
risk_df = pd.read_csv("risk_trend_data.csv")

risk_df["date"] = pd.to_datetime(risk_df["date"])
risk_df = risk_df.sort_values("date").reset_index(drop=True)

latest = risk_df.iloc[-1]

geopolitical_risk = latest["risk_score"]


# ============================================================
# GEOPOLITICAL CONTEXT
# ============================================================

# These are configuration values.
# The risk engine itself is not Iran-specific.

country = "Iran"
region = "Middle East"


# ============================================================
# SECTOR EXPOSURE TO IMPORT DISRUPTION
# ============================================================

sectors = {
    "Energy": {
        "exposure": 90,
        "relevance": 1.00,
        "reason": (
            "High dependence on imported crude oil, "
            "petroleum and gas."
        )
    },

    "Food Commodities": {
        "exposure": 40,
        "relevance": 0.30,
        "reason": (
            "Moderate exposure to disruptions in "
            "selected food supply chains."
        )
    }
}


# ============================================================
# CALCULATE SECTOR RISK
# ============================================================

results = []

for sector, data in sectors.items():

    sector_risk = (
        geopolitical_risk
        * (data["exposure"] / 100)
        * data["relevance"]
    )

    # Keep score between 0 and 100
    sector_risk = max(0, min(100, sector_risk))

    if sector_risk >= 70:
        category = "HIGH"
    elif sector_risk >= 40:
        category = "MEDIUM"
    else:
        category = "LOW"

    results.append({
        "sector": sector,
        "risk": sector_risk,
        "category": category,
        "exposure": data["exposure"],
        "relevance": data["relevance"],
        "reason": data["reason"]
    })


# ============================================================
# OVERALL INDIA IMPACT
# ============================================================

highest_risk = max(results, key=lambda x: x["risk"])

overall_impact = highest_risk["risk"]

if overall_impact >= 70:
    overall_category = "HIGH"
elif overall_impact >= 40:
    overall_category = "MEDIUM"
else:
    overall_category = "LOW"


# ============================================================
# OUTPUT
# ============================================================

print()
print("=" * 46)
print("       INDIA IMPORT EXPOSURE")
print("=" * 46)

print()
print(f"Geopolitical Risk : {geopolitical_risk:.2f}")
print(f"Country / Entity  : {country}")
print(f"Region            : {region}")


print()
print("-" * 46)
print("         SECTOR IMPORT RISK")
print("-" * 46)

for result in results:

    print(
        f"{result['sector']:<25} "
        f"{result['risk']:>6.2f} "
        f"{result['category']}"
    )


print()
print("-" * 46)
print("              DETAILS")
print("-" * 46)

for result in results:

    print()
    print(result["sector"])

    print(f"Risk       : {result['risk']:.2f}")
    print(f"Category   : {result['category']}")
    print(f"Exposure   : {result['exposure']}")
    print(f"Relevance  : {result['relevance']:.2f}")
    print(f"Reason     : {result['reason']}")


# ============================================================
# INDIA IMPACT SUMMARY
# ============================================================

print()
print("-" * 46)
print("          INDIA IMPORT IMPACT")
print("-" * 46)

print(f"Overall Impact : {overall_category}")
print(f"Impact Score   : {overall_impact:.2f}")

print()
print(f"Primary Vulnerability : {highest_risk['sector']}")

print()
print("Why it matters:")
print(highest_risk["reason"])


print()
print("=" * 46)
print("             END OF ANALYSIS")
print("=" * 46)